name = "ratelimit-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[[ d1_databases ]]
binding = "DB"
database_name = "ratelimit-db"
database_id = "33fba40f-abcc-43b1-b931-04baca75462b"

[vars]
ENVIRONMENT = "production"
JWT_SECRET = "your-secret-key-change-this"
